name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy backend to EC2
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/backend/linkedin-scrape-data

            # Pull latest backend code
            git pull origin main

            # Install Node.js deps
            npm install

            # Install Python deps (if needed)
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi

            # Restart backend with PM2
            pm2 restart backend || pm2 start server.js --name backend

            # Save PM2 process list
            pm2 save
          EOF
