name: Deploy Backend to EC2

on:
  push:
    branches: [main]  # Changed from 'master' to 'main'
    # paths:           # Optional: Uncomment if you want path filtering
    #   - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}  # Reuse existing key
          known_hosts: "just-a-placeholder"

      - name: Deploy & Restart Backend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            echo "➡️  Navigating to backend directory..."
            cd ~/backend/linkedin-scrape-data || {
              echo "❌ Error: Backend directory not found!";
              ls -la ~/backend;
              exit 1;
            }

            echo "🔄 Pulling latest code..."
            git pull origin main

            echo "📦 Installing Node.js dependencies..."
            npm install

            echo "🐍 Installing Python dependencies (if any)..."
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi

            echo "🚀 Restarting PM2 process..."
            pm2 restart backend || pm2 start server.js --name backend
            pm2 save

            echo "📜 Latest PM2 logs:"
            pm2 logs backend --lines 20 --nostream

            echo "✅ Backend deployed successfully!"
          EOF
