name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "Setting up SSH..."
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/deploy_key
          chmod 600 $HOME/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: Deploy backend to EC2
        run: |
          ssh -i $HOME/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "Connected to EC2"

            cd ~/backend/linkedin-scrape-data

            echo "Pulling latest code..."
            git fetch origin master && git reset --hard origin/master

            echo "Installing Node dependencies..."
            npm install

            if [ -f requirements.txt ]; then
              echo "Installing Python dependencies..."
              python3 -m pip install -r requirements.txt
            fi

            echo "Starting backend with PM2..."
            which pm2 || npm install -g pm2
            pm2 restart backend || pm2 start server.js --name backend
            pm2 save
          EOF
