name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/deploy_key
          chmod 600 $HOME/.ssh/deploy_key
          ssh-keyscan ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: Deploy backend to EC2
        run: |
          ssh -i $HOME/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/backend/linkedin-scrape-data

            git fetch origin master && git reset --hard origin/master

            npm install

            if [ -f requirements.txt ]; then
              python3 -m pip install -r requirements.txt
            fi

            which pm2 || npm install -g pm2

            pm2 restart backend || pm2 start server.js --name backend

            pm2 save
          EOF
